name: Publish docker image

on:
  push:
    tags: "*"

jobs:
  docker_x86:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build ubuntu-latest x64
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Display OS architecture
        run: uname -a
      - name: Docker registry login [ghcr.io]
        env:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: docker login $registry -u $username -p $password
      - name: Build Docker image
        env:
          registry: ghcr.io
          image_name: ${{ github.repository }}/home_guardian
        run: docker build -t $registry/$image_name:$GITHUB_REF_NAME-x86 .
      - name: Push Docker image
        env:
          registry: ghcr.io
          image_name: ${{ github.repository }}/home_guardian
        run: docker push $registry/$image_name:$GITHUB_REF_NAME-x86
      - name: List Docker image
        run: docker image list | grep $image_name

  docker_armv7:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: buster
          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          env: |
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            image_name: ${{ github.repository }}/home_guardian
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            docker login $registry -u $username -p $password
            docker build -t $registry/$image_name:$GITHUB_REF_NAME-buster .
            docker push $registry/$image_name:$GITHUB_REF_NAME-buster
            docker image list | grep $image_name
