name: Publish docker image

on:
  push:
    tags: "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker Image to GitHub Packages [Container Registry - ghcr.io]
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}/home_guardian
          push_git_tag: true
